name: Accessibility Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Mondays

jobs:
  a11y:
    name: Accessibility Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}

      - name: Start server
        run: npm start &
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}

      - name: Wait for server
        run: npx wait-on http://localhost:3000 -t 60000

      - name: Run axe accessibility tests
        run: |
          npm install -g @axe-core/cli
          axe http://localhost:3000 --exit --tags wcag2a,wcag2aa --stdout
          axe http://localhost:3000/dogs --exit --tags wcag2a,wcag2aa --stdout
          axe http://localhost:3000/details?id=dog1 --exit --tags wcag2a,wcag2aa --stdout

      - name: Stop server
        if: always()
        run: pkill -f "node" || true

