name: Performance Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 3' # Run weekly on Wednesdays

jobs:
  performance:
    name: Performance Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}

      - name: Start server
        run: npm start &
        env:
          NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}

      - name: Wait for server
        run: npx wait-on http://localhost:3000 -t 60000

      # Using Lighthouse CI instead of the non-existent web-vitals-reporter
      - name: Run Lighthouse performance tests
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            http://localhost:3000
            http://localhost:3000/dogs
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Stop server
        if: always()
        run: pkill -f "node" || true

